Models/ErrorViewModel.cs
using System;

namespace MvcAlexSeriesExamen.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/ListaSeriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MvcAlexSeriesExamen.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlexSeriesExamen.Models
{
    public class ListaSeriesViewComponent : ViewComponent
    {

        private ServiceSeries service;

        public ListaSeriesViewComponent(ServiceSeries service)
        {
            this.service = service;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Serie> series = await this.service.GetSeriesAsync();
            return View(series);
        }

    }
}

Models/Personaje.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlexSeriesExamen.Models
{
    [Table("PERSONAJES")]
    public class Personaje
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("IDPERSONAJE")]
        public int IdPersonaje { get; set; }
        [Column("PERSONAJE")]
        public string NombrePersonaje { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
        [Column("IDSERIE")]
        public int IdSerie { get; set; }
    }
}

Models/Series.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlexSeriesExamen.Models
{
    [Table("SERIES")]
    public class Serie
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("IDSERIE")]
        public int IdSerie { get; set; }
        [Column("SERIE")]
        public string NombreSerie { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
        [Column("PUNTUACION")]
        public double Puntuacion { get; set; }
        [Column("AÑO")]
        public int Year { get; set; }

    }
}

Models/UsuarioAzure.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlexSeriesExamen.Models
{
    [Table("USUARIOSAZURE")]
    public class UsuarioAzure
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column("IDUSUARIO")]
        public int IdUsuario { get; set; }
        [Column("NOMBRE")]
        public string NombreUsuario { get; set; }
        [Column("APELLIDOS")]
        public string Apellidos { get; set; }
        [Column("EMAIL")]
        public string Email { get; set; }
        [Column("PASS")]
        public string Password { get; set; }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MvcAlexSeriesExamen.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlexSeriesExamen.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PersonajesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcAlexSeriesExamen.Models;
using MvcAlexSeriesExamen.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlexSeriesExamen.Controllers
{
    public class PersonajesController : Controller
    {
        ServicePersonajes service;
        ServiceSeries ss;
        public PersonajesController(ServicePersonajes service, ServiceSeries ss)
        {
            this.service = service;
            this.ss = ss;
        }
        public async Task<IActionResult> AddPersonaje()
        {
            List<Serie> series = await this.ss.GetSeriesAsync();
            ViewData["SERIES"] = series;
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddPersonaje(string nombre, string imagen, int idserie)
        {
            List<Serie> series = await this.ss.GetSeriesAsync();
            ViewData["SERIES"] = series;
            await this.service.AddPersonaje(nombre, imagen, idserie);

            return RedirectToAction("GetSeries", "Series");
        }


        public async Task<IActionResult> GetPersonajesSerie(int idserie)
        {
            List<Personaje> personajes = await this.service.PersonajesSerie(idserie);
            return View(personajes);
        }

        public async Task<IActionResult> CambioSerie()
        {
            List<Personaje> personajes = await this.service.GetPersonajesAsync();
            List<Serie> series = await this.ss.GetSeriesAsync();
            ViewData["LP"] = personajes;
            ViewData["LS"] = series;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CambioSerie(int idpersonaje, int idserie)
        {
            await this.service.CambiarSerie(idpersonaje, idserie);

            return RedirectToAction("GetSeries", "Series");
        }


    }
}

Controllers/SeriesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcAlexSeriesExamen.Models;
using MvcAlexSeriesExamen.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcAlexSeriesExamen.Controllers
{
    public class SeriesController : Controller
    {
        ServiceSeries service;
        public SeriesController(ServiceSeries service)
        {
            this.service = service;
        }


        public async Task<IActionResult> GetSeries()
        {
            List<Serie> series = await this.service.GetSeriesAsync();
            return View(series);
        }

        public async Task<IActionResult> Details(int idserie)
        {
            Serie serie = await this.service.FindSerieAsync(idserie);
            return View(serie);

        }


    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Personajes/AddPersonaje.cshtml
@model MvcAlexSeriesExamen.Models.Personaje

@{
    ViewData["Title"] = "AddPersonaje";
    List<Serie> series = ViewData["SERIES"] as List<Serie>;
}

<h1>AddPersonaje</h1>

<h4>Personaje</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPersonaje">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="NombrePersonaje" class="control-label"></label>
                <input name="nombre" class="form-control" />
                <span asp-validation-for="NombrePersonaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Imagen" class="control-label"></label>
                <input name="imagen" class="form-control" />
                <span asp-validation-for="Imagen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Series :</label>
                <select name="idserie" class="form-control">
                    @foreach (var item in series)
                    {
                        <option value="@item.IdSerie">@item.NombreSerie</option>
                    }
                </select>
                <span asp-validation-for="IdSerie" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Personajes/CambioSerie.cshtml
@{
    ViewData["Title"] = "CambioSerie";
    List<Personaje> personajes = ViewData["LP"] as List<Personaje>;
    List<Serie> series = ViewData["LS"] as List<Serie>;
}

<h1>Cambio Serie</h1>

<form method="post" class="card p-3">
    <label>Personaje :</label>
    <select name="idpersonaje" class="form-control">
        @foreach (var item in personajes)
        {
            <option value="@item.IdPersonaje">@item.NombrePersonaje</option>
        }
    </select>
    <br />
    <label>Serie:</label>
    <select name="idserie" class="form-control">
        @foreach (var item in series)
        {
            <option value="@item.IdSerie">@item.NombreSerie</option>
        }
    </select>
    <br />
    <button class="btn btn-success">Guardar Cambios</button>
</form>

Views/Personajes/GetPersonajesSerie.cshtml
@model IEnumerable<MvcAlexSeriesExamen.Models.Personaje>

@{
    ViewData["Title"] = "GetPersonajesSerie";
}

<h1>GetPersonajesSerie</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdPersonaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombrePersonaje)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdSerie)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdPersonaje)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombrePersonaje)
                </td>
                <td>
                    <img src="@item.Imagen" style="width:250px ; height:250px" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdSerie)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Series/Details.cshtml
@model MvcAlexSeriesExamen.Models.Serie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Serie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdSerie)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdSerie)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NombreSerie)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NombreSerie)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.Imagen" style="width:250px; height:250px;" />

        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Puntuacion)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Puntuacion)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-success" asp-action="GetPersonajesSerie" asp-controller="Personajes" asp-route-idserie="@Model.IdSerie">Ver Personajes</a>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Series/GetSeries.cshtml
@model IEnumerable<MvcAlexSeriesExamen.Models.Serie>

@{
    ViewData["Title"] = "GetSeries";
}

<h1>GetSeries</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdSerie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NombreSerie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Puntuacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdSerie)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NombreSerie)
                </td>
                <td>
                    <img src="@item.Imagen" style="height:250px ; width:250px" />

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Puntuacion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/Components/ListaSeries/Default.cshtml
@model List<Serie>

<div class="dropdown-menu">
    @foreach (var item in Model)
    {
        <a asp-action="Details" class="dropdown-item" asp-controller="Series" asp-route-idserie="@item.IdSerie">@item.NombreSerie</a>
    }
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcAlexSeriesExamen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcAlexSeriesExamen</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Personajes" asp-action="AddPersonaje">Nuevo personaje</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Personajes" asp-action="CambioSerie"> Personajes/Series</a>
                        </li>

                    </ul>
                </div>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Series
                    </button>
                    @await Component.InvokeAsync("ListaSeries")
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MvcAlexSeriesExamen - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>